### ISSUE TITLE
Empty toSend response

### ISSUE THREAD

**Issue by rosscdh** [TTLabs/EvaporateJS#103]
Hi there, using angular-evaporate and tracking the request though to the evaporate.js library I get to a point where we try to evaluate the payload. However the payload is always null...

var payload = requester.toSend ? requester.toSend() : null;

Any thoughts with this would be appreciated.

<img width="1281" alt="screen shot 2016-01-15 at 16 32 50" src="https://cloud.githubusercontent.com/assets/397106/12356974/c1b03970-bba5-11e5-86f3-9f7d95e92f8e.png">

**Comment by bikeath1337** [comment]
@rosscdh , then only two use cases for toSend are the Upload Part and Complete methods. For the part upload, the toSend returns the part body to upload; the Complete use case returns the XML constructed to tell AWS to sew all the parts together and close the upload.

Otherwise, toSend() will indeed return `null`. You seem to be evaluating the payload for Initiate which has no payload.

**Comment by rosscdh** [comment]
Thanks
