### ISSUE TITLE
Include policy field in request, optional signerUrl

### ISSUE THREAD

**Issue by jakubzitny** [TTLabs/EvaporateJS#197]
Hey @bikeath1337, I have two questions regarding policies and signatures when uploading to S3, it's probably little bit similar to #145.

If we want to upload to S3 via HTTP and look into [Amazon docs](http://docs.aws.amazon.com/AmazonS3/latest/dev/HTTPPOSTForms.html#HTTPPOSTFormFields) we find following info about:
`policy`
> Security policy describing what is permitted in the request. Requests without a security policy are considered anonymous and will succeed only on publicly writable buckets.

and `signature`
> The HMAC signature constructed by using the secret access key that corresponds to the provided AWSAccessKeyId. This field is required if a policy document is included with the request.

When using Evaporate, we get the signature from `signerUrl`, but is it possible to include the `policy` as well? Is it needed? You mentioned in #145 that it's not, but that only seems to be the case when having "public" s3, or not?

Another thing: is it possible to have `signerUrl` optional and return the `signature` from `signResponseHandler` manually?

Let's say we already have a lot of code that deals with authentication to our backend, allocating an "upload slot" to S3 and returning policy/signature. It has different "api" than `to_sign` and `timestamp`. Right now I am replacing  whatever is returend from `signerUrl` in `signResponseHandler`. However, it would be cool to skip the useless request to `signerUrl` if we don't want it. What do you think?

**Comment by bikeath1337** [comment]
I am not an expert in everything S3 but from what I gather, when using AWS RESTful endpoints, the policy is determined on the server and not part of the request. The policy is part of the browser-based form uploads, I believe.

That being said, there are ways to specify things like access in the request but to be honest, this would be a question for AWS support. Just tell them that you're using an API that implements http://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html and see what they say. If its possible via headers, then it's possible that Evaporate may support it.

You could also pose the question like so: "we currently do this...and if we move to a solution based on the REST API and multipart uploads with MD5 checksums, what can we reuse?"

Apologies if I'm saying something you already know but this is how I would approach AWS for expert advice.

Note, when reading the docs at the above link, we don't use the part labeled "http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-UsingHTTPPOST.html" because we do the part splitting and transfer using Ajax, not through the browser's form. (I'm pretty sure the form style doesn't allow parallel uploads, but again, trust AWS, not not my experience).

Many thoughts come to mind as I write but let's start with the above and see what comes back. I think the focus should be on what you're trying to achieve and then figure out how to do it. Hopefully, Evaporate will make life easier.

**Comment by bikeath1337** [comment]
So, let me restate. What you are reading is how to upload a single file through the browser's built-in upload via a Form object. Since most of the heavy lifting is done by the form, AWS provides you with ways to pack everything into the form as inputs and headers.

Evaporate uses the REST API, which works on a lower level that does not relay on the browser's built-in FORM logic but rather on pure ajax using a FileReader/Blob. This is why we can do parallel uploads and keep track of the progress of each part.

So my logic is as follows: if the FORM style gives you certain advantage related to authentication, the question to answer is how should that be done with the REST API. I think the answer will be in the fact that you have to control the signature generation and can deny the generation based on your own business rules...that's just my initial guess. Off to bed.

**Comment by jakubzitny** [comment]
Thanks for the response, I'll ping AWS support and look more into it.

What about the other thing? Do you think it makes sense to make `signerUrl` optional?

>Another thing: is it possible to have `signerUrl` optional and return the `signature` from `signResponseHandler` manually?

>Let's say we already have a lot of code that deals with authentication to our backend, allocating an "upload slot" to S3 and returning policy/signature. It has different "api" than `to_sign` and `timestamp`. Right now I am replacing whatever is returend from `signerUrl` in `signResponseHandler`. However, it would be cool to skip the useless request to `signerUrl` if we don't want it. What do you think?

**Comment by bikeath1337** [comment]
I think I need a better understanding of what you're doing and would prefer to help you on a hangout or Skype call.

**Comment by bikeath1337** [comment]
This should be satisfied by the release of v1.5.4.
