### ISSUE TITLE
It doesn't upload same file in different folder

### ISSUE THREAD

**Issue by mario-areias** [TTLabs/EvaporateJS#210]
Ok, this one is definitely weird (and again not sure if is a real issue). When I am uploading files to S3, I am specifying the folder where I want the upload to happen. I do this by specifying the folder in the file name as done here (not quite sure if that's the right way to do it):

```js
var uploadId = evaporate.add({
                name: randomId + '/' + file.name,
                file: file
         }
```

This works great for the first time. However, when I try to upload it again in a different folder and `allowS3ExistenceOptimization` is true, the `HEAD` request runs against the old folder name, so then the upload doesn't even start because Evaporate thinks the file is already uploaded. The problem is related to the code below.

```js
function uploadKey(fileUpload) {
            // The key tries to give a signature to a file in the absence of its path.
            // "<filename>-<mimetype>-<modifieddate>-<filesize>"
            return [
                fileUpload.file.name,
                fileUpload.file.type,
                dateISOString(fileUpload.file.lastModifiedDate),
                fileUpload.file.size
            ].join("-");
        }
```

At this point the `fileUpload` object has the field `name` with the right value: `new-folder/file.jpg`. However, to create the upload key instead to use `fileUpload.name` Evaporate is using `fileUpload.file.name`. Which returns the file name only (`file.jpg`) and therefore when looking at the `localStorage` it returns the old upload id with the old folder name. So then the `HEAD` request is done and S3 returns that the file exists and the upload to the new folder doesn't even start.

I wonder if the way I am setting the folder name is correct and if it is, if we shouldn't use the full path as a part of the key instead of the file name only.

**Comment by Masterdanielsan** [comment]
It probably won't suffice, but one option might be to set **onlyRetryForSameFileName: true** for now.  That option seems to ignore the upload parts if the filename has a new prefix.

**Comment by mario-areias** [comment]
Thanks @Masterdanielsan . I will try that, so this is really an issue then? Should I open a PR using `fileUpoad.name` instead of `fileUpload.file.name` in the `uploadKey` function?

**Comment by bikeath1337** [comment]
The purpose of re-using the uploaded file is to support this use-case: customer uploads multiple very large files (say video) and all of those files need to be stitched together on the server side after all of the large files are uploaded to S3. If the customer loses connectivity or refreshes the browser, they would have to re-upload all of their files again, even though they already uploaded that file using a unique key.

If you do not want this feature, then you should use `onlyRetryForSameFileName` option or completely disable the `allowS3ExistenceOptimization ` option.

By the way, both of these options default to false, so simply removing them from your Evaporate instantiation call, should suffice.

**Comment by mario-areias** [comment]
Thanks for the info @bikeath1337. However, I am not quite sure how the current behaviour helps them. If they refresh the browser they want to keep the file in the same folder, right? If they are uploading to a different folder, they want a different upload. For instance, an admin of a website want to upload several `logo.jpgs` in different folder for her clients.  In this case, the upload wouldn't happen after the first file is uploaded. 

I can do as you said, but I am not quite sure if that's a good behaviour. But anyway, you know better than I do. 

If I remove the `allowS3ExistenceOptimization` and leave the `onlyRetryForSameFileName` as true and `s3FileCacheHoursAgo` enabled as well that would avoid to upload a file that already exists in a folder, right?

**Comment by mario-areias** [comment]
> If I remove the allowS3ExistenceOptimization and leave the onlyRetryForSameFileName as true and s3FileCacheHoursAgo enabled as well that would avoid to upload a file that already exists in a folder, right?

That didn't work. It just uploads again, although the file is already there.

**Comment by bikeath1337** [comment]
Folders don't exist on S3, just buckets and keys. What you are calling  a folder is actually a key to a file in a _bucket_ (the bucket is part of the local key for good reason!). We can't use the key locally since you regenerate it randomly each time. You seem to be using a random number to improve performance of S3 PUTS, per the AWS guidelines (that's great!) but you're not creating folders.

If browsers were to give us access to the full file path, that would help matters a lot, but that is explicitly not allowed for security reasons.

The existence optimization has to use whatever it has available about the _local_ file name (without the path), including it's timestamp and size. Because the S3 key is randomized and could never be used as a lookup (the key given to S3 for the upload will be _different_ for each upload of the _same_ file).

The optimization takes the eTag of the successfully uploaded file, along with the available local data about the file, to determine if the file has been uploaded. If it has been uploaded, the `complete` callback will let you immediately know the S3 object key that was found instead (the object key of the object on S3 that did not need to be uploaded) (see the readme on this one).

**Comment by mario-areias** [comment]
Thanks a lot for the explanation @bikeath1337! I was confused a bit, because in S3 console, I saw the random ids as folders. I will just do as you suggest and will close this. 

Thanks again!

**Comment by bikeath1337** [comment]
Sure thing, Mario, I know it's a bit confusing to understand the file names when using random ids AND the need to recover.
