### ISSUE TITLE
Uploads are not Working for IE

### ISSUE THREAD

**Issue by Masterdanielsan** [TTLabs/EvaporateJS#214]
Problem was mentioned in #208 and while the first issue was fixed, uploads still do not work on Internet Explorer (11).

I have tested uploads on Chrome, Firefox, Opera, and IE.  IE is the only one in which I cannot upload to s3.  There is a signature mismatch.  I imagine it has to do with a different to_sign string getting generated.  Possibly in the hashed payload portion. 

Can someone confirm this bug?

**Comment by bikeath1337** [comment]
To troubleshoot what may be wrong with the signature on IE, compare the response error XML from AWS against the signature component output from Evaporate when logging: true. One of those components of the signature may be off, for example, the date format.

**Comment by dangerous** [comment]
I have the same issue.  I'm unfamiliar with debugging in IE and I haven't had much time to look at this issue, but it looks to me like IE is not sending the `Authorization` header.

**Comment by dangerous** [comment]
It's actively stripping it.  If I break at that point where Evaporate calls `xhr.setRequestHeader('Authorization', authorizationMethod(requester));`, and then in the console call `xhr.setRequestHeader('AAAAuthorization', authorizationMethod(requester));`, I will see the `AAAAuthorization` header but not the `Authorization` header.

**Comment by dangerous** [comment]
OK, no it's not.  Because of quirks of the IE dev tools implementation, the Authorization header is not displayed.  It is sent however, and can be viewed using Fiddler.  Alternatively, commenting it out in the code will result in an Authorization failed from AWS, and we are seeing a Signature Mismatch.

No, the truth is another quirk of IE, the `pathname` function should return a string with a leading slash, but in IE it doesn't.  I have submitted a PR for this which fixes the issue and makes uploads work in IE, at least for me.

https://github.com/TTLabs/EvaporateJS/pull/220
