### ISSUE TITLE
Call timeUrl only if needed — RequestTimeTooSkewed or on config

### ISSUE THREAD

**Issue by jakubzitny** [TTLabs/EvaporateJS#228]
Hi, my colleague had good point when we talked about Evaporate's `timeUrl`. A good enhancement (default or via option) to Evaporate would be to call `timeUrl` for checking date/time only when S3 returns `RequestTimeTooSkewed` possibly indicating that user's time is incorrect.

One of the reasons of using `timeUrl` is to handle cases when users have incorrect time which might cause inability to upload to S3 at all. Correct me please if I am wrong, but I think this is the main reason for having `timeUrl`.

So if a developer wants to handle this case inside inside Evaporate, he provides a `timeUrl` to his backend. However, he doesn't need this url to be called all the time — that's waste of requests. The best would be to call it only when its needed, that is when S3 returns `RequestTimeTooSkewed`.

What do you think?

**Comment by bikeath1337** [comment]
I see that point of view. It was originally implemented as a _synchronous_ hook on each call to AWS. Since it's only purpose was to avoid `RequestTimeTooSkewed`, the idea of calling it once per Evaporate instance, was worth the round trip and a drop in the bucket of the many requests that play a role in uploading with multipart upload.

An error hook would work, too, no doubt. It's benefits would be as you describe, but the down side would be even more complication of the code base and an exception around error handling, which already a bit brittle (!). There is so much asynchronous activity going on, that adding one more layer, makes me a bit concerned.
