### ISSUE TITLE
Problem with parts when connection is offline and back online

### ISSUE THREAD

**Issue by jakubzitny** [TTLabs/EvaporateJS#241]
If I recall correctly, Evaporate used to work with temporarily lost connection. When I try it now, it still picks up after the connection is restored, but when sending 'complete' request to S3 it fails on `InvalidPart`.

```
<Error>
<Code>InvalidPart</Code>
<Message>One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag.</Message>
<UploadId>...</UploadId>
<PartNumber>3</PartNumber>
<ETag />
<RequestId>...</RequestId>
<HostId>...</HostId>
</Error>
```

I tried it with the latest and previous version and it is happening on both. I am investigating more..

**Comment by bikeath1337** [comment]
In the tests I did, we specifically tested for this repeatedly and did not see this issue. Off the top of my head, this happens if the part number or the part Etag do not match what was sent with the actual  PUT of the part.

I will look closer with this report but any additional information you can give me about the conditions that make it happen would be great. Thanks!

**Comment by jakubzitny** [comment]
Thanks for the reply @bikeath1337. I think this is actually problem in my code. Right now, I am using Evaporate's master with two commits I added on top of that. One is already in #232 and another one is similar where I am passing headers for both GET requests.

The reason why this is happening is that I am passing a `x-amz-security-token` header to the request in `getUploadParts`. The token shouldn't be in that request at all. So when I remove it, everything works as it should.

Sorry for false alarm. Closing this.

**Comment by bikeath1337** [comment]
Thanks!

**Comment by jakubzitny** [comment]
Actually, when I don't pass the `x-amz-security-token` header to the request in `getUploadParts` I am having problems with uploading a file with the same name.

So the original issue is probably valid, the headers should be passed there and if they're there, I am getting the `InvalidPart` fails. I will try to investigate all part requests and their ETags on Tuesday..

**Comment by bikeath1337** [comment]
This is probably related to our earlier discussion that not all evaporate AWS request go through the same processing and one of the drivers behind the tests so we can confidently refactor the requests to use a common processing framework.

I made a patch several months ago, when refining the file existence optimization. SHA 67b849d8a added the signparams but didn't store the signheaders probably because no one has tried to use that feature until recently. :)

**Comment by bikeath1337** [comment]
I can reproduce this and will work on a fix for it. thanks @jakubzitny .
