### ISSUE TITLE
Allow support detection without instantiating an Evaporate object

### ISSUE THREAD

**Issue by tremby** [TTLabs/EvaporateJS#243]
I want to detect support on a page where I'm not actually using Evaporate, so have not instantiated it. But it appears that the `supported` property doesn't exist on the class, only on the instance.

I currently have to run `(new Evaporate({signerUrl: 'x', bucket: 'x'})).supported` to test it (since without either parameter it errors), and this is rather unintuitive.

**Comment by bikeath1337** [comment]
One of the reasons why it's not on the class is that if users don't apply checksums, then the supported browser list is purportedly larger since the browser does not have to support "readAsArrayBuffer".

This last check is only apply when instantiating Evaporate as otherwise, that supported feature would not be required.

**Comment by bikeath1337** [comment]
Of course, all of that is a bit moot if we really think that everyone ought to use the checksums. I' be for adding the class-level feature in the upcoming refactor project.

**Comment by tremby** [comment]
Ah, that makes sense. So in my case I should in fact be instantiating it properly (with all the right configuration) before making the check.

**Comment by tremby** [comment]
...or at least with the checksums enabled. What's the minimum configuration I should pass?

**Comment by bikeath1337** [comment]
Yes, that is what I would do given how this version works.

**Comment by tremby** [comment]
For any looking, the minimal configuration appears to be this:

    new Evaporate({
        signerUrl: 'x',
        bucket: 'x',
        computeContentMd5: true,
        cryptoMd5Method: function() {},
    }).supported

**Comment by bikeath1337** [comment]
For the record, `signerUrl`, `computeContentMd5` are optional. `cryptoMd5Method` is only required when `computeContentMd5` is set. The readme was updated recently to describe the minimum options:

https://github.com/TTLabs/EvaporateJS#new-evaporate

Otherwise, you're configuration is the minimal configuration with checksums enabled, which is what I would strongly recommend as well. I would also set the `cloudfront` option.

**Comment by tremby** [comment]
Without `signerUrl`, "Option signerUrl is required unless signResponseHandler is present."

`computeContentMd5` is necessary to test for support when using that feature, which I am.
