### ISSUE TITLE
Signed Headers not being passed

### ISSUE THREAD

**Issue by jessica-pixvana** [TTLabs/EvaporateJS#258]
I'm trying to pass in headers to my signerUrl. And it doesn't seem to be working. Can someone point me in the right direction?

If I console.log(xhr.headers) right before: https://github.com/TTLabs/EvaporateJS/blob/master/evaporate.js#L1474 I get undefined

```
    let _e_ = new Evaporate({
        signerUrl: signUrl
        awsRegion: AWS.config.region,
        aws_key: AWS.config.credentials.accessKeyId,
        bucket: bucket,
        awsSignatureVersion: '4',
        aws_url:s3Url,
        computeContentMd5: true,
        encodeFilename: false,
        cryptoMd5Method: function (data) { return AWS.util.crypto.md5(data, 'base64'); },
        cryptoHexEncodedHash256: function (data) { return AWS.util.crypto.sha256(data, 'hex'); },
        logging: true,
        signHeaders: {'Authorization':token}
    });
```

**Comment by bikeath1337** [comment]
Hi, @jessica-pixvana . XMLHttpRequest doesn't expose the headers you set with .setRequestHeader, so I would expect your debug line to show `undefined`. That info is probably a red herring.

What version are you using? You should be on 1.5.2 but I'd strongly recommend 1.5.8.

If you use `signedHeaders`, it may change the CORS security for the request and throw an error on the OPTIONS. In that case, you'll never see the request headers in the browser debug windows.

Are you able to see the actual request headers in your browser debug tools or does the preflight OPTIONS method for the request fail?

If there is an OPTIONS error, then you've got to address the security issues created by adding the "new" request headers.

If none of the above apply, we'll keep digging.

**Comment by jessica-pixvana** [comment]
I am on 1.5.8.  I cannot see the headers in the debug tools because the preflight OPTIONS fails. What do you mean by "new" request headers?

I really appreciate your help!

**Comment by bikeath1337** [comment]
Thanks for the additional information. Tested this yesterday and confirmed in my tests that Evaporate is correctly setting the headers. Initially it didn't work because the request failed at the OPTIONS preflight request, too. This ALWAYS means that you're breaking a CORS rule.

So...you need to go to your server that receives the signing request and make sure it's allowing the new request through.

The reason it was working before was that the default configuration does not trigger CORS validation. As soon as you added an authorization header, that's related to security, CORS will step in unless your signing server explicitly allows the new request headers.

**Comment by bikeath1337** [comment]
In other words, if your example follows what I did, then Evaporate is working. The requests will succeed once your signing server properly responds to the preflight OPTIONS request.

**Comment by bikeath1337** [comment]
I added a test for this to demonstrate that the signHeaders are indeed passed by Evaporate.
