### ISSUE TITLE
Available upload slots

### ISSUE THREAD

**Issue by cvn** [TTLabs/EvaporateJS#273]
I maintain my own upload queue outside of evaporate. I only want to add files to evaporate if there are available upload slots.

I do this because I hit my server before each file uploaded to get a unique id, and use that in the filename on s3. By maintaining my own queue, I can create these ids as necessary instead of all at the beginning. In this way, I minimize the mess that is left behind when an upload session is interrupted.

I had a technique that worked, described in [#267](https://github.com/TTLabs/EvaporateJS/issues/267#issuecomment-263776177), but it doesn't work as well in the latest release, 2.0.0-rc.7.

Would you consider supporting a way to communicate the number of available upload slots?

**Comment by bikeath1337** [comment]
Let me start by thanking you for your detailed testing and feedback regarding the release candidates for v2.0. It was invaluable in improving the iterations.

---------
Evaporate needs to manage the queue of slots and probably would never expose that for manipulation by a developer because if you don't behave correctly, the entire upload process is blown to hell. Besides, the target audience for Evaporate is a developer who doesn't want to roll their own, but use a stable and tried solution that parallelizes uploads, makes them recoverable and resumable and in such a way that the uploaded file is an exact copy of the original. The control of upload slots is one of the 'secret sauces' of the library.

But let me answer your two main concerns that seem to have influence your decision: 

1. creating a (unique) object key on S3 in advance is problematic because
2. interrupted uploads create a mess

## Point 1
_(the below has some implicit assumptions. if they do not apply, please do not assume that I know better than you do about what you need)_

Let's start with 1. How many files are you / your users uploading at once? I've seen anything from 1 to 400 files for video stitching applications. If you are like most clients, the object key you create starts with a randomized string (per S3 performance recommendations) and hopefully is guaranteed to not clash with another user's file name if you're sharing buckets in a multi-tenant configuration.

It is not until the object key is actually used to start an upload that you really care at all, right? Because you probably want to translate that unique object name to something user-friendly; map it to the user's file name and associate the (not completed) upload with your backend. The `started` and `nameChanged` callbacks tell you when evaporate has created a multipart upload on S3 and those are the callbacks that you generally use to make the association between the user's file and the object on S3. In this scenario, I do not see any benefit in creating unique object keys "just in time" because there is an infinite pool of unique object names.

_If_ you let Evaporate manage the slots, it will tell you when each file is completed, and, _if you choose,_ you can use those returned Promised to do something when all are complete.

## Point 2
Evaporate does its best to keep you from making a "mess". You can (and probably should) give the user control to cancel an upload. You can (and probably should) use Evaporate's failed upload resumption features with a smallish part size IMO because it's such a time saver to recover from interrupted uploads. And if you haven't already implemented the newish S3 lifecycle policy rule that automatically frees resources associated with stale and incomplete uploads, you probably should.

To manage the mess, if you allow users to cancel uploads, you probably need to notify your backend that the user wants to cancel. In pseudo code using Promises, the logic would look something like this:

```javascript

// tell your backend to relinquish references to the upload
// then tell evaporate to relinquish all and any data associated with the upload
function cancelOnBackend(uploadId) {
  return new Promise(function (resolve, reject) {
    $.ajax('/cancel')
        .then(resolve);
  });
}
$.click()
  .then(function () {
      return cancelOnBackend(uploadId);
   })
  .then(function () {
     evaporate.cancel(uploadKey);
   })
```
I at peace with the reality that I have no control to prevent  a user's browser from crashing; their connectivity disappearing or to keep them from accidentally browsing away from an upload window. You always have to deal with that reality, regardless of whether pre-generate unique keys or do them in a roll-your-own way. With these three safeguards processes in place, the only mess that gets created is cleaned up by the S3 policy.

Evaporate at least makes the recovery of an upload sort of magical.

**Comment by cvn** [comment]
Wow, Thank you for taking the time. And I'm happy the feedback has been helpful.

My object key is based on my item's url slug (a hash). I'm fond of this generally, but I can also see the advantages of a decoupled approach to collision avoidance. I will give it some thought.

The mess I was talking about is just the unused item stubs in my db, which are only an issue with uncontrolled interruptions.

For now, I'm comfortable tracking changes to the internals of evaporate in order to find out how many slots are available. I figured out what I had to change for rc.7 and my needs are simple enough that I think it will be sustainable going forward.

Looking through the source, I found the `config.evaporateChanged` function, and since it's called when evaporatingCount changes, it's useful for the kind of nonsense I'm doing. I'll use this opportunity to make a request to keep it around. Otherwise, I think you can close this ticket. Thank you again.

**Comment by bikeath1337** [comment]
Very welcome! I do want to close by being clear that Evaporate attempts to adhere to semantic versioning. This means that we'll update the version number to indicate a breaking change to the developer-facing features. The internals of Evaporate may change at any time and this change may not be indicated in the version number if the internal changes do not impact the published behavior, meaning your application may break.
