### ISSUE TITLE
Website freezing while uploading files

### ISSUE THREAD

**Issue by ElPincheTopo** [TTLabs/EvaporateJS#274]
When I'm uploading a file with EvaporateJS the interface of my website freezes from time to time, I think it is while creating the MD5 checksum. It works ok, but when you put the mouse on top of a link or something it takes a couple of seconds to change from the pointer to the little hand that appears on links.

I'm signing with V4 which requires the MD5 to be used.

Am I doing something wrong? Is there a way to avoid the freeze?

**Comment by bikeath1337** [comment]
@ElPincheTopo Thanks for the question. I've not had any reports about browsers freezing but given that the MD5 calculation is CPU-instensive, the chances of pausing would increase, I assume. 

The cost of the digest calculation increases with the size of the part and could depend on the crypto library you're using.  My recommendation would be to use the default part size. The overhead of negotiating each new part is negligible compared to the overall perfection of transfer, redundancy and recovery benefits you get from Evaporate's implementation.

**Comment by ElPincheTopo** [comment]
@bikeath1337 Thanks for the reply. After testing it in other browsers, it looks like it's just happening in Chrome on Linux. I'll take your advice and use the default part size.

**Comment by bikeath1337** [comment]
Great. Thanks. I hope you have time to try out v2.0!

**Comment by Martinsos** [comment]
Hi @bikeath1337 , thanks for this great library :)!
I am using evaporate 2.1.4.

When testing it on Chrome on Linux, I am getting drop of FPS for half a second or so before each chunk starts uploading. I replicated the same problem on Chrome on OSX.

For this, I was using:
```javascript
  computeContentMd5: true,
  cryptoMd5Method: (data) => AWS.util.crypto.md5(data, 'base64'),
  cryptoHexEncodedHash256: (data) => AWS.util.crypto.sha256(data, 'hex')
```

and I figured, this is probably happening due to MD5 calculation taking all the CPU, which was also confirmed when I run performance analysis in developer console.

I then updated `cryptoMd5Method` to this (and replaced AWS md5 method with SparkMD5):
```javascript
cryptoMd5Method: async (data) => {
  const spark = new SparkMD5.ArrayBuffer()
  const md5ChunkSize = 256 * 1024  // 256 KB
  for (let start = 0; start < data.byteLength; start += md5ChunkSize) {
    await new Promise((resolve) => setTimeout(() => {
      spark.append(data.slice(start, start + md5ChunkSize))
      resolve()
    }, 15))
  }
  return btoa(spark.end(true))
}
```
so that MD5 is executed in smaller chunks which are scheduled with setTimeout, so that browser can also execute other tasks in the meantime.

This fixed issue in Chrome on OSX, however issue still remains on Chrome on Linux! I tried Firefox on Linux, and that works fine.

I played a lot with value of md5ChunkSize and value of delay and so on, and nothing helps. I am starting to believe that there is something else happening in EvaporateJS at the beginning of MD5 calculation that is making browser freeze, maybe reading from disk?? But in performance analysis there is nothing visible, at least I did not catch anything -> it seems as if nothing is executing during the "freeze".

Photo of performance analysis:

![evaporate-upload-freeze](https://user-images.githubusercontent.com/1536647/41597234-1eb8b106-73cd-11e8-98e3-f9ebf048bb9b.png)

My questions:

1. Problem with MD5 taking all CPU sounds like smt that others should also be experiencing, how big of a problem is that for another users? How are they solving it? Also chunking like this? Maybe by using Web Worker, is that an option? Do you have any guidelines regarding this?
2. Do you have any suggestions how to debug this issue with Chrome on Linux? I can run some more tests or dig in somewhere, if you have some suggestions / pointers.

Thanks!

**Comment by ElPincheTopo** [comment]
@Martinsos I use to have your same problem when using big partSize. Now I use 5Mb and I don't really have this issue anymore. What are you using as partSize?

**Comment by Martinsos** [comment]
@ElPincheTopo At the beginning I used default, which is 6MB I believe. Then I set it to 5MB since that is the lowest it can go, and that improves it a little bit but not too much. I never used bigger parts than this.
I actually tried going with 1MB and uploading itself was working better, but it was also throwing errors because that is too small part size for S3 so upload was not really completing. But it also makes sense why it works better -> instead of freezeing for half a second every X secs, now it freezes for 0.1 sec every X / 6 secs, so it is less visible. But the problem is still there.
