### ISSUE TITLE
S3 upload id

### ISSUE THREAD

**Issue by pauldijou** [TTLabs/EvaporateJS#285]
According to [AWS documentation](http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadInitiate.html#RespElemInitMPUpload), when starting a new multipart upload, a unique id is assigned to it. You can then use it to list already uploaded parts or delete them.

The use case is to store this id in our DB so that we can easily delete parts from admin panel when an upload is considered too old (user closed its browser before finishing it and never restarted it).

Is there a way to get this id when using Evaporate?

**Comment by bikeath1337** [comment]
It would definitely be possible to expose the upload id and originally this was on the list of feature candidates to be used exactly as you suggest; However, since AWS started supporting an S3 Life Cycle bucket policy that automatically sweeps the buckets for incomplete uploads, there seemed to be no pressure to support it. I think this is because it takes a lot of work to clean up, particularly if your use base is significant. Rolling your own clean up tool also potentially creates the risk of deleting an upload that really is in progress.

I used to have a clean up scripts but I mothballed them as soon as I created the life cycle policies (which, btw, were really easy to create).

https://aws.amazon.com/blogs/aws/s3-lifecycle-management-update-support-for-multipart-uploads-and-delete-markers/

**Comment by pauldijou** [comment]
That's exactly what I wanted to do at first but couldn't. We are working on a collaborative tool and we need to track all ongoing uploads to both display progress to all users and to lock some uploads to prevent concurrent upload for a specific target (if a project need the A file and the B file, only one user should be able to upload the A file at a given time).

If we automatically cleanup S3 storage, it might be hard to synchronize with our DB locks. We also have a button to cancel an ongoing upload (both deleting the lock and the S3 parts). That's why it would be super convenient to have the S3 id to delete those parts.

I was thinking about having the id in the `started` callback eventually.

**Comment by bikeath1337** [comment]
I definitely see the value in that. I've always tried to treat Evaporate as a black box that manages the complexity of S3 multipart uploads, so I've tried not to expose internals too much, but the existing codebase has tests and coverage for dealing with situations where the upload is messed with by external events.

Initially I agreed that the `started` callback would be a good place to start but it gets called before the multipart upload is initialized and it sends the internal id as its parameter.

So now I would lean towards a new method so as to not risk breaking any usage of Evaporate by current users...or something completely new, an addition, rather than a change.

**Comment by pauldijou** [comment]
Any news about that? Do you want me to try a PR? (don't know much about Evaporate...) I was thinking about a synchronous function that takes the Evaporate id and returns the AWS id or `undefined` if the upload didn't start yet (just need to store the AWS id inside whatever object you are using to track the upload)

**Comment by bikeath1337** [comment]
I would go ahead and create a PR that is modeled against the .started callback. Its parameter would be the uploadID I think.

**Comment by bikeath1337** [comment]
@pauldijou see #306

**Comment by pauldijou** [comment]
Thanks a lot !
