### ISSUE TITLE
sign_url call too many times when upload 50 GB file

### ISSUE THREAD

**Issue by pratik2pris** [TTLabs/EvaporateJS#289]
Hello 

I am trying to upload 50 GB file and I found that the sign_url call every 500 ms / every part . Too much calls will increase too much memory footprint locally and also too much around 1000+ sign_url calls to server which cause to too much load on server.

Can you let me know if any configuration can avoid above issue ?

**Comment by bikeath1337** [comment]
@pratik2pris , which version are you using? It's important because memory retention was an issue we dealt with for awhile but it has been resolved.

Every request to AWS must be signed. There is no way to work around that. 500ms seems pretty costly but I suppose that has to do with your implementation and is something out of bounds of Evaporate. That being said...for each part, you're going to get a call to your sign_url, which means, if you're using the default part size, you're sending about 806 signing requests + init + complete.

If you're seeing memory retention, I suspect you need to upgrade. Still, 500ms for signature is not cheap, so I would look at ways to improve response times there, if possible (I realize this has nothing to do with the memory retention) because a back of the envelope calculation says you're spending about 7 minutes just signing your requests.

You could use a larger part size to reduce the number of part signatures; however, until you use a version that improves memory retention, that's not going to help.

**Comment by pratik2pris** [comment]
I was using old version 2.0.3 and yes now I will try latest version.




On Jan 4, 2017 10:33 PM, "Bobby Wallace" <notifications@github.com> wrote:

@pratik2pris <https://github.com/pratik2pris> , which version are you
using? It's important because memory retention was an issue we dealt with
for awhile but it has been resolved.

Every request to AWS must be signed. There is no way to work around that.
500ms seems pretty costly but I suppose that has to do with your
implementation and is something out of bounds of Evaporate. That being
said...for each part, you're going to get a call to your sign_url, which
means, if you're using the default part size, you're sending about 806
signing requests + init + complete.

If you're seeing memory retention, I suspect you need to upgrade. Still,
500ms for signature is not cheap, so I would look at ways to improve
response times there, if possible (I realize this has nothing to do with
the memory retention) because a back of the envelope calculation says
you're spending about 7 minutes just signing your requests.

You could use a larger part size to reduce the number of part signatures;
however, until you use a version that improves memory retention, that's not
going to help.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/TTLabs/EvaporateJS/issues/289#issuecomment-270425076>,
or mute the thread

**Comment by bikeath1337** [comment]
Thank you. I would appreciate it if you could let me know if it addressed the issues.

If that works, the only way to reduce your cost of signing would be to increase your part size and optimize your signer. If you increase your part size, you should expect a larger footprint and time to generate the checksum. Going by the math, if you increased the part size to 12MB, then you'll potentially reduce the upload cost by 3 minutes.

**Comment by bikeath1337** [comment]
Thanks, I am going to close this Issue, then. Could you open a _**new issue related to the max utilization question**_? I think this issue would better suit the community as a new thread.

BTW, thank you for providing insight into behavior on a fat pipe. My pipe is not so fat and I am able to saturate it. My guess is that you're experiencing a limitation to how your browser works, but we shall see.

Other note: 100 MB part size is large but probably makes sense for your fat pipe. What memory pressures, if any are you seeing and are you noticing a delay to calculate the checksum for the parts? My experience has been (anecdotally) that a partsize > 50MB MD5 calculation is noticeably slower.

**Comment by pratik2pris** [comment]
Ok. I am going to create new issue related to max utilization.
