### ISSUE TITLE
Unable to complete upload if partSize < filesize

### ISSUE THREAD

**Issue by ile** [TTLabs/EvaporateJS#298]
I set the partSize to 16 * 1024 and the file upload doesn't seem to be finished successfully. It stops at 100 % but doesn't actually finish the whole process. It keeps "sitting" at 100 %.

I can inspect further where it stops, but this is for now what I have seen.

BTW, why is the default partSize at 6 MB, isn't that a whole lot? I mean, my motivation to use Evaporate is for mobile, and I would assume a partsize around 100 - 200 kb would be better? Re-uploading parts that are in megabytes would take a long time?

**Comment by bikeath1337** [comment]
@ile This was a known issue several versions back but not for the latest version. It is really essential that for each issue you create, you provide full information about which version of evaporate you are using and the essentials of how you configured and added the file to upload.

Please review the AWS Multipart Upload docs for the reasoning for why they require a minimum part size of 5MB. Evaporate, for some historical reason, chose to set the default slightly higher.

I personally would not agree that 100 - 200 kb would be a good part size because of the number of parts that would have to be generated for a largish size and this would add additional overhead to the entire upload.

**Comment by ile** [comment]
Ok, didn't know that. Then this upload method isn't for me after all.

Maybe add a test if someone tries to set too low partSize?

Probably incorrect bug report. I'll close this.

**Comment by ile** [comment]
Google Drive has 256 KB minimum part size.

iPhone may autolock in a minute, and that's why I need a resumable upload with a smallish part size. There isn't any way to prevent the autolock that I have found that would work for me. I can't use the location.href refresh method.

**Comment by bikeath1337** [comment]
https://github.com/TTLabs/EvaporateJS/issues/301 Added!

**Comment by bikeath1337** [comment]
@ile See https://github.com/TTLabs/EvaporateJS/issues/266 as it relates to Google Drive. The rest of the EvaporateJS community may be able to help you out here.
