### ISSUE TITLE
Is there a native equivalent of EvaporateJS for iOS and Android?

### ISSUE THREAD

**Issue by YMIndustries** [TTLabs/EvaporateJS#311]
Hi,

I realise this is probably the wrong place to ask this, I just didn't know where else to ask and everyone here seems pretty friendly.

I've implemented AWS Multipart Uploads in my webapp using EvaporateJS, and now I want to implement the same thing on my native iOS and Android apps. But when I tried using the official AWS SDK I found that it requires a Cognito Identity in order to make uploads. I really want to reuse my existing signing URL that I created for EvaporateJS in order to handle my native client uploads too. Is there a library or some way that I can achieve this? I'd like to avoid writing all the upload handling code myself.

Thanks,

YM_Industries

**Comment by bikeath1337** [comment]
@YMIndustries EvaporateJS was originally designed for browser uploads to make it easier to use the S3 multipart upload. The AWS javascript SDK would work otherwise on its own but it still doesn't support md5 checksums on binary files. Your best source for help would be AWS support or Stackoverflow, I think. (Note that your question is independent from Evaporate, so you can broaden your search for better results).

The other SDK are (usually) usually fully implemented. In the case of iOS, that SDK already fully supports the multipart upload through the [TransferManager](http://docs.aws.amazon.com/mobile/sdkforios/developerguide/s3transfermanager.html). I don't know if it supports md5 checksums, but would assume it does. All the other evaporate features like pause, resume, cancel, are all built into that SDK.

Additionally, due to the different nature of iOS apps, the signing methods are, as you noted, different.  Instead of trying to force a JavaScript API solution on iOS, I might try to "embrace" how the iOS SDK works or integrate it into your infrastructure for the most stable solution.

**Comment by YMIndustries** [comment]
Thanks for the recommendations! I knew this wasn't the place to ask (I already asked at StackOverflow) but I knew this would be the place where people understood what I wanted most easily. I hope you don't mind my creating an issue here, and thanks very much for your reply.

I might have to use the way the iOS SDK works, but it feels much messier to me. Having to create a new Cognito Identity for each upload, give it selective permissions to only upload the authorised file, detect when the upload is complete and erase it, or clean it up after a timeout period, it seems like a lot of moving parts. I love the way that with EvaporateJS I just make an API endpoint which checks the permissions itself and then signs or refuses the request. It feels less 'stateful'.

I'm going to try to replicate your approach on iOS and Android, but if it's too challenging I will make a solution around Cognito Identities instead. I hope you take it as a compliment that I am so impressed with the tidiness of your 3rd party solution that now I can't stand the official Amazon way.

**Comment by bikeath1337** [comment]
Thank @YMIndustries , I really appreciate the compliment. Let's hope that EvaporateJS can continue to grow and be used in the community!
