### ISSUE TITLE
Temporary Credentials

### ISSUE THREAD

**Issue by Masterdanielsan** [TTLabs/EvaporateJS#315]
I have a question when getting EvaporateJS to work with Temporary Credentials:

Currently, my signerUrl returns a single signature, but from what I understand, I also need to set the **'x-amz-security-token': security_token** in order for S3 to accept a file-part that was signed with a temporary key (EC2 Instance using an IAM role).

How am I supposed to set this **security_token** in evaporate each time it gets a new signature for a file part?  Doesn't the token change each time the temporary credentials get cycled? Am I missing something?

**Comment by bikeath1337** [comment]
According to [Using Temporary Security Credentials to Request Access to AWS Resources](http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html), "The temporary credentials expire after a specified interval. After the credentials expire, any calls that you make with those credentials will fail, so you must get a new set of credentials."

So if the AWS documentation is accurate, you do not get a new security token for each request but a an expirable security token is returned. This is what you supply through`xAmzHeadersCommon`. If AWS change the security token per request, then EvaporateJS does not support this.

If I were to guess, you are incorrectly requesting a new security token for each request, rather than requesting a security token for the session and then using that token when configuration EvaporateJS.

**Comment by Masterdanielsan** [comment]
Thank you for clearing this up.

Are the xAmzHeadersCommon included in the string-to-sign (Are they signed headers)?  I'm wondering about reconfiguring the security token every so often to allow for really long upload sessions that may last longer than the token is active.  In this case, I would want to reset the header to the new token.

I'm worried about getting mismatches this way that would cause the upload to stall out. Any thoughts on this matter? Thanks!

**Comment by bikeath1337** [comment]
Set `xAmzHeadersCommon` to include the security token. As per the AWS documentation, which you would do well to read, the x-amz-headers are included in the string to sign and ultimately the signature.

If you want to change the security token, then get a new token and use that token in subsequent requests.

If you have really long requests, you could consider asking AWS to provide a longer-lived token.

**Comment by Masterdanielsan** [comment]
Always a pleasure, @bikeath1337. Thank you for your help.
