### ISSUE TITLE
computeContentMd5: false memory issue

### ISSUE THREAD

**Issue by pratik2pris** [TTLabs/EvaporateJS#335]
I am using large file for upload as previously discussed and with computeContentMd5: true it is working well but return AWS.util.crypto.md5(data, 'base64'); takes time to calculate checksum.

So I am trying with computeContentMd5: false option. But I found that it has memory issue. e.g. It is not release the memory after complete part.

If I use computeContentMd5: true it release the memory after each part done.

Can you help me ?

**Comment by bikeath1337** [comment]
You should be using `computeContentMd5`. If you are using Evaporate in a web worker, it's been reported to not work. Otherwise, as long as you keep your part size to about 6-12 MB, you shouldn't see any 'unreasonable' delay. However...calculating the checksum is not free but the trade off is robustness and recoverability.

**Comment by bikeath1337** [comment]
Thank you for the report @pratik2pris . I just merged a fix to the retained memory issue.
