### ISSUE TITLE
Upload doesn't fail if acceleration is not enabled in s3, but evaporate config is enabled

### ISSUE THREAD

**Issue by GitShaffi** [TTLabs/EvaporateJS#369]
Upload doesn't fail if acceleration is not enabled in s3 but the evaporate config is set to enabled.
Getting the below message with error code 400 from S3. 

`<Code>`InvalidRequest`</Code>`
`<Message>` S3 Transfer Acceleration is disabled on this bucket `</Message>`

This should eventually fail the upload, but it keeps on retrying unnecessarily.

**Comment by bikeath1337** [comment]
That is a valid point; however, there are a large number of possible errors that could be detected. Many of them are mainly caused during setup, trying to apply the correct privileges, etc., and once resolved, are no longer an issue. We chose to not complicate the codebase further with a list of errors that might need to be retried or not and instead use the unlimited retry approach because this provided the greatest ability to provide robust uploads on intermittent connections.

**Comment by bikeath1337** [comment]
I am going to close this issue. For those who find this issue, the moral of the story is: when setting up Evaporate and AWS S3, make sure to view the error XML AWS returns. If the message relates to configuration, please change the configuration to fix the error.

Evaporate is designed to retry indefinitely but it is not set up to add convenience methods to point out configuration issues that should only occur during development and initial setup.
