### ISSUE TITLE
Does EvaporateJS support parallel multi-part uploads?

### ISSUE THREAD

**Issue by pdebaets** [TTLabs/EvaporateJS#64]
Thanks for your work here, this is just what I am looking for.
Does EvaporateJS support parallel multi-part uploads?

**Comment by tomsaffell** [comment]
@pdebaets it currently does not supporting concurrent file uploads - they go into a queue. it does support concurrent uploads of parts (for which ever file it's working on). 

the reason is: if there are multiple files uploading at once then each will have a longer total elapsed time, which means the probability of a part failure increases, which increases (on average) the total upload time for the two files. 

please can you elaborate on the use case for which you need concurrent file uploads? perhaps if i understand that better i can think about it for a future version. thanks.

**Comment by pdebaets** [comment]
Thanks for getting back to me Tom. My concern is speed of uploads. I've seen the S3 Browser that advertises high-speed multi-part uploads and downloads and I wondered if EvaporateJS offered the same thing.

**Comment by tomsaffell** [comment]
@pdebaets to the best of my knowledge, speed is maximized by having multiple concurrent network requests, and that's achieved by having multiple concurrent parts, w/o multiple concurrent files. 

if you're really interested in speed, then try playing with the `part size`, that's probably where the low hanging fruit is

**Comment by Ryan-Anderson** [comment]
For bulk upload UI, I find that the concurrent uploads provides a better experience. To accomplish this you can simply instantiate new `Evaporate` objects.

Here is an example:

```
var evaporators = [ ];

 // Create up to 5 evaporators for concurrency
if (evaporators.length < 5) {
    evaporators.push(new Evaporate(JSON.parse(jsonConfig)));
} else {
    var shifted = evaporators.shift();
    evaporators.push(shifted);
}

evaporators[evaporators.length - 1].add({
    ....
})
```
